const players=[["David",5],["Davyd",6],["Eryk",6],["Linus",7],["Emil",7],["Tobias",7],["Max",8],["Olai",4],["Isak",7],["Lavrans",3],["Johannes",3],["Mikael",1],["Mikkel",4],["Daniel",1],["Olav",3],["Evo",2],["Thomas",5],["Samuel",4],["Leo",4]].map(([name,level],i)=>({id:`p${i}`,name,level}));
const state={selected:new Set(players.map(p=>p.id)),conflicts:[],together:[],teams:[]};
const $=id=>document.getElementById(id);
const label=id=>{const p=players.find(x=>x.id===id);return players.filter(x=>x.name===p.name).length>1?`${p.name} (${p.level})`:p.name};
function summary(){const n=state.selected.size;$("selectionSummary").textContent=`${n} valgt`;$("playerStatus").textContent=`${n} av ${players.length} deltar`;$("toggleAll").textContent=n===players.length?"Fjern alle":"Velg alle";const r=state.conflicts.length+state.together.length;$("rulesStatus").textContent=r?`${r} ${r===1?"regel":"regler"} lagt til`:"Ingen regler lagt til"}
function renderPlayers(){const q=$("playerSearch").value.toLowerCase();$("playerList").replaceChildren(...players.filter(p=>p.name.toLowerCase().includes(q)).map(p=>{const b=document.createElement("button");b.className=`player${state.selected.has(p.id)?" active":""}`;b.setAttribute("aria-pressed",state.selected.has(p.id));b.innerHTML=`<span class="check">✓</span><span class="name">${label(p.id)}</span><span class="level">${p.level}</span>`;b.onclick=()=>{state.selected.has(p.id)?state.selected.delete(p.id):state.selected.add(p.id);renderPlayers();summary()};return b}))}
function controls(id,type){const box=$(id),a=document.createElement("select"),b=document.createElement("select"),add=document.createElement("button");[a,b].forEach(s=>players.forEach(p=>s.add(new Option(label(p.id),p.id))));b.selectedIndex=1;add.textContent="+";add.setAttribute("aria-label","Legg til regel");add.onclick=()=>addPair(type,a.value,b.value);box.replaceChildren(a,b,add)}
function addPair(type,a,b){const list=state[type],other=state[type==="conflicts"?"together":"conflicts"],match=p=>(p[0]===a&&p[1]===b)||(p[0]===b&&p[1]===a);$("message").textContent="";if(a===b){$("message").textContent="Velg to forskjellige spillere.";return}if(other.some(match)){$("message").textContent="De samme spillerne kan ikke både skilles og spille sammen.";return}if(!list.some(match))list.push([a,b]);renderRules();summary()}
function ruleList(id,type,symbol){$(id).replaceChildren(...state[type].map((pair,i)=>{const b=document.createElement("button");b.className="chip";b.title="Fjern regel";b.innerHTML=`${label(pair[0])} ${symbol} ${label(pair[1])}<span>×</span>`;b.onclick=()=>{state[type].splice(i,1);renderRules();summary()};return b}))}
function renderRules(){ruleList("conflictList","conflicts","/");ruleList("togetherList","together","+")}
function generate(){const count=Number($("numTeams").value),active=players.filter(p=>state.selected.has(p.id));$("message").textContent="";if(active.length<count){$("message").textContent=`Velg minst ${count} spillere for å lage ${count} lag.`;return}const teams=Array.from({length:count},()=>[]);active.sort((a,b)=>b.level-a.level||Math.random()-.5).forEach(p=>{const ranked=teams.map((team,index)=>{const conflict=state.conflicts.some(pair=>pair.includes(p.id)&&team.some(x=>pair.includes(x.id))),partner=state.together.some(pair=>pair.includes(p.id)&&team.some(x=>pair.includes(x.id)));return{index,score:team.reduce((s,x)=>s+x.level,0)+team.length*8+(conflict?1000:0)-(partner?100:0)+Math.random()}}).sort((a,b)=>a.score-b.score);teams[ranked[0].index].push(p)});state.teams=teams;renderTeams()}
function renderTeams(){const colors=["#fb7185","#60a5fa","#34d399","#fbbf24","#c084fc","#fb923c"];$("teams").replaceChildren(...state.teams.map((team,i)=>{const card=document.createElement("article");card.className="team";card.style.setProperty("--team",colors[i]);const score=team.reduce((s,p)=>s+p.level,0);card.innerHTML=`<div class="teamHead"><strong>Lag ${i+1}</strong><span>${team.length} spillere · ⚡ ${score}</span></div><ul>${team.map(p=>`<li><span>${label(p.id)}</span><small>nivå ${p.level}</small></li>`).join("")}</ul>`;return card}));$("results").classList.remove("hidden");$("results").scrollIntoView({behavior:"smooth"})}
document.querySelectorAll(".panelToggle").forEach(b=>b.onclick=()=>{const panel=b.closest(".panel"),content=$(b.getAttribute("aria-controls")),open=b.getAttribute("aria-expanded")==="true";b.setAttribute("aria-expanded",!open);content.hidden=open;panel.classList.toggle("open",!open)});
$("playerSearch").oninput=renderPlayers;$("toggleAll").onclick=()=>{state.selected.size===players.length?state.selected.clear():players.forEach(p=>state.selected.add(p.id));renderPlayers();summary()};
function setCount(n){n=Math.max(2,Math.min(6,n));$("numTeams").value=n;$("teamCountOutput").textContent=n}$("decreaseTeams").onclick=()=>setCount(+$('numTeams').value-1);$("increaseTeams").onclick=()=>setCount(+$('numTeams').value+1);$("generate").onclick=generate;$("regenerate").onclick=generate;
controls("conflictControls","conflicts");controls("togetherControls","together");renderPlayers();renderRules();summary();
