const players=[["David",5],["Davyd",6],["Eryk",6],["Linus",7],["Emil",7],["Tobias",7],["Max",8],["Olai",4],["Isak",7],["Lavrans",3],["Johannes",3],["Mikael",1],["Mikkel",4],["Daniel",3],["Olav",3],["Evo",2],["Thomas",5],["Samuel",4],["Leo",4]].map(([name,level],i)=>({id:`p${i}`,name,level}));
const state={selected:new Set(players.map(p=>p.id)),conflicts:[],together:[],teams:[]};
const $=id=>document.getElementById(id);
const label=id=>{const p=players.find(x=>x.id===id);return players.filter(x=>x.name===p.name).length>1?`${p.name} (${p.level})`:p.name};
function summary(){const n=state.selected.size;$("selectionSummary").textContent=`${n} valgt`;$("playerStatus").textContent=`${n} av ${players.length} deltar`;$("toggleAll").textContent=n===players.length?"Fjern alle":"Velg alle";const r=state.conflicts.length+state.together.length;$("rulesStatus").textContent=r?`${r} ${r===1?"regel":"regler"} lagt til`:"Ingen regler lagt til"}
function renderPlayers(){const q=$("playerSearch").value.toLowerCase();$("playerList").replaceChildren(...players.filter(p=>p.name.toLowerCase().includes(q)).map(p=>{const b=document.createElement("button");b.className=`player${state.selected.has(p.id)?" active":""}`;b.setAttribute("aria-pressed",state.selected.has(p.id));b.innerHTML=`<span class="check">✓</span><span class="name">${label(p.id)}</span>`;b.onclick=()=>{state.selected.has(p.id)?state.selected.delete(p.id):state.selected.add(p.id);renderPlayers();summary()};return b}))}
function controls(id,type){const box=$(id),a=document.createElement("select"),b=document.createElement("select"),add=document.createElement("button");[a,b].forEach(s=>players.forEach(p=>s.add(new Option(label(p.id),p.id))));b.selectedIndex=1;add.textContent="+";add.setAttribute("aria-label","Legg til regel");add.onclick=()=>addPair(type,a.value,b.value);box.replaceChildren(a,b,add)}
function addPair(type,a,b){const list=state[type],other=state[type==="conflicts"?"together":"conflicts"],match=p=>(p[0]===a&&p[1]===b)||(p[0]===b&&p[1]===a);$("message").textContent="";if(a===b){$("message").textContent="Velg to forskjellige spillere.";return}if(other.some(match)){$("message").textContent="De samme spillerne kan ikke både skilles og spille sammen.";return}if(!list.some(match))list.push([a,b]);renderRules();summary()}
function ruleList(id,type,symbol){$(id).replaceChildren(...state[type].map((pair,i)=>{const b=document.createElement("button");b.className="chip";b.title="Fjern regel";b.innerHTML=`${label(pair[0])} ${symbol} ${label(pair[1])}<span>×</span>`;b.onclick=()=>{state[type].splice(i,1);renderRules();summary()};return b}))}
function renderRules(){ruleList("conflictList","conflicts","/");ruleList("togetherList","together","+")}
function generate(){const count=Number($("numTeams").value),active=players.filter(p=>state.selected.has(p.id));$("message").textContent="";if(active.length<count){$("message").textContent=`Velg minst ${count} spillere for å lage ${count} lag.`;return}const teams=Array.from({length:count},()=>[]);active.sort((a,b)=>b.level-a.level||Math.random()-.5).forEach(p=>{const ranked=teams.map((team,index)=>{const conflict=state.conflicts.some(pair=>pair.includes(p.id)&&team.some(x=>pair.includes(x.id))),partner=state.together.some(pair=>pair.includes(p.id)&&team.some(x=>pair.includes(x.id)));return{index,score:team.reduce((s,x)=>s+x.level,0)+team.length*8+(conflict?1000:0)-(partner?100:0)+Math.random()}}).sort((a,b)=>a.score-b.score);teams[ranked[0].index].push(p)});state.teams=teams;renderTeams()}
function renderTeams(){const colors=["#fb7185","#60a5fa","#34d399","#fbbf24","#c084fc","#fb923c"];$("teams").replaceChildren(...state.teams.map((team,i)=>{const card=document.createElement("article");card.className="team";card.style.setProperty("--team",colors[i]);card.innerHTML=`<div class="teamHead"><strong>Lag ${i+1}</strong><span>${team.length} spillere</span></div><ul>${team.map(p=>`<li><span>${label(p.id)}</span></li>`).join("")}</ul>`;return card}));$("results").classList.remove("hidden");$("results").scrollIntoView({behavior:"smooth"})}
document.querySelectorAll(".panelToggle").forEach(b=>b.onclick=()=>{const panel=b.closest(".panel"),content=$(b.getAttribute("aria-controls")),open=b.getAttribute("aria-expanded")==="true";b.setAttribute("aria-expanded",!open);content.hidden=open;panel.classList.toggle("open",!open)});
$("playerSearch").oninput=renderPlayers;$("toggleAll").onclick=()=>{state.selected.size===players.length?state.selected.clear():players.forEach(p=>state.selected.add(p.id));renderPlayers();summary()};
function setCount(n){n=Math.max(2,Math.min(6,n));$("numTeams").value=n;$("teamCountOutput").textContent=n}$("decreaseTeams").onclick=()=>setCount(+$('numTeams').value-1);$("increaseTeams").onclick=()=>setCount(+$('numTeams').value+1);$("generate").onclick=generate;$("regenerate").onclick=generate;
const exercises=[
 {category:"warmup",emoji:"🚦",title:"Rødt og grønt lys",focus:"Alle samlet · opptil 20",time:"7 min",equipment:"Én ball per spiller",setup:"Lag et stort firkantet område. Alle står inni området med hver sin ball.",steps:["Rop «grønt» – alle fører ballen fritt.","Rop «rødt» – alle stopper ballen med foten.","Start igjen med en gang. Legg eventuelt til «gul» for sakte fart."],tip:"Forklar bare rødt og grønt først. Ingen går ut, og ingen poeng telles."},
 {category:"warmup",emoji:"🐒",title:"Hermegåsa med ball",focus:"Alle samlet · opptil 20",time:"6 min",equipment:"Én ball per spiller",setup:"Alle har ball og god plass. Treneren står synlig foran gruppen.",steps:["Treneren viser én enkel bevegelse.","Alle hermer: tåtouch, stopp med sålen eller føring rundt seg selv.","Bytt bevegelse hvert 30. sekund."],tip:"Vis mer enn du snakker. Bruk bare bevegelser barna får til med én gang."},
 {category:"warmup",emoji:"🏠",title:"Finn et ledig hus",focus:"Alle samlet · opptil 20",time:"7 min",equipment:"Baller og 12–16 kjegler",setup:"Lag små «hus» av to kjegler rundt i området. Det kan være færre hus enn spillere.",steps:["Alle fører ballen rundt mellom husene.","Når treneren klapper, finner alle et hus og stopper ballen der.","Start straks på nytt. Det er lov å dele hus."],tip:"Ingen blir slått ut. Flytt kjeglene lenger fra hverandre hvis det blir mye kollisjoner."},
 {category:"warmup",emoji:"🦈",title:"Haien kommer",focus:"Alle samlet · opptil 20",time:"8 min",equipment:"Én ball per spiller og vester",setup:"Marker et stort område. Alle har ball, mens to trenere eller spillere er haier.",steps:["Alle fører ballen fritt.","Haiene prøver å berøre en ball med foten.","Blir ballen tatt, gjør spilleren tre tåtouch og fortsetter."],tip:"Ingen står på siden. Bytt haier ofte og gjør området større hvis det blir uoversiktlig."},
 {category:"small",emoji:"🚪",title:"Drible gjennom porter",focus:"Gruppe på 3–5",time:"8 min",equipment:"Baller og 8 kjegler",setup:"Lag fire små porter. Alle har hver sin ball.",steps:["Før ballen gjennom en valgfri port.","Finn deretter en annen port.","Hvor mange porter klarer gruppen samlet på ett minutt?"],tip:"Tell gruppens total, ikke hvem som er best. Da hjelper barna hverandre."},
 {category:"small",emoji:"🔺",title:"Pasning i trekant",focus:"Gruppe på 3–4",time:"8 min",equipment:"Én ball og tre kjegler",setup:"Sett tre kjegler i en liten trekant. Én spiller ved hver kjegle, og en ekstra spiller deler plass.",steps:["Spill ballen til neste kjegle.","Følg etter egen pasning.","Hold ballen i gang uten å telle feil."],tip:"Kort avstand gir mestring. Vis innsiden av foten og la barna starte med å stoppe ballen først."},
 {category:"small",emoji:"🎯",title:"Skyt ned kjeglene",focus:"Gruppe på 3–5",time:"8 min",equipment:"Én ball hver og høye kjegler",setup:"Sett fire kjegler på en linje. Spillerne står 4–6 meter unna.",steps:["Alle prøver å velte en ledig kjegle.","Hent egen ball og still kjeglen opp igjen.","Fortsett uten kø."],tip:"Sørg for nok baller. Flytt barna nærmere hvis få treffer."},
 {category:"small",emoji:"⚔️",title:"Én mot én til to mål",focus:"Gruppe på 3–5",time:"10 min",equipment:"Fire kjeglemål og baller",setup:"Lag en liten bane med to mål i hver ende. To spiller, resten hviler med ball i få sekunder.",steps:["Treneren eller neste spiller setter ballen i gang.","Spilleren med ball kan score i ett av to mål.","Etter scoring eller uteball kommer neste spiller raskt inn."],tip:"Runder på 20–30 sekunder gir lite venting. Spør bare: «Hvor er det ledig?»"},
 {category:"small",emoji:"⚽",title:"Smålagsspill",focus:"Gruppe på 3–5",time:"15 min",equipment:"To små mål, vester og baller",setup:"Lag en bane på omtrent 10 × 15 meter. Spill én mot én eller to mot to. Med fem spillere kan én være joker på laget som har ballen.",steps:["Start med ny ball med en gang den gamle går ut.","La barna spille uten mange stopp.","Bytt lag eller joker etter 3–4 minutter."],tip:"Dette bør få mest tid. Små lag gir mange ballberøringer og avslutninger."}
];
function exerciseCard(x){const card=document.createElement("details");card.className="exercise";card.innerHTML=`<summary><span class="exerciseEmoji">${x.emoji}</span><span class="exerciseTitle"><strong>${x.title}</strong><small>${x.focus}</small></span><span class="exerciseArrow">⌄</span></summary><div class="exerciseBody"><div class="exerciseMeta"><span>⏱ ${x.time}</span><span>🎒 ${x.equipment}</span></div><h3>Oppsett</h3><p>${x.setup}</p><h3>Slik gjør dere</h3><ol>${x.steps.map(step=>`<li>${step}</li>`).join("")}</ol><p class="coachTip"><strong>Trenertips:</strong> ${x.tip}</p></div>`;return card}
function renderExercises(){const list=$("exerciseList");list.replaceChildren();[["warmup","Oppvarming","Én trener kan styre hele gruppen samlet"],["small","Hoveddel i små grupper","Del inn i grupper på 3–5 og bruk som stasjoner"]].forEach(([category,title,text])=>{const section=document.createElement("section");section.className="exerciseGroup";section.innerHTML=`<div class="exerciseGroupTitle"><strong>${title}</strong><small>${text}</small></div>`;exercises.filter(x=>x.category===category).forEach(x=>section.appendChild(exerciseCard(x)));list.appendChild(section)})}
$("showExercises").onclick=()=>{const panel=$("exercisesPanel"),toggle=panel.querySelector(".panelToggle"),content=$("exercisesContent");toggle.setAttribute("aria-expanded","true");content.hidden=false;panel.classList.add("open");panel.scrollIntoView({behavior:"smooth",block:"start"})};
controls("conflictControls","conflicts");controls("togetherControls","together");renderPlayers();renderRules();renderExercises();summary();
